version: "3.9"

services:
  client:
    build:
      context: .
      args:
        REACT_APP_API_URL: ${http://host.docker.internal:8000}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: learning-platform-client:latest
    ports:
      - "8080:80"
    restart: unless-stopped